version: '3.8'

services:
  neo4j:
    image: neo4j:5.26.15-community-bullseye
    container_name: my_neo4j
    ports:
      - 7474:7474 # ブラウザ経由でhttp://localhost:7474でアクセスするとNeo4jのコンソールにアクセスできる
      - 7687:7687 # プログラム経由でNeo4jにアクセスするためのポート
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
    networks:
      - mynetwork
  worker-lambda:
    build:
      context: ./worker_lambda
    container_name: worker-lambda
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4jpassword
    ports:
      - 10000:8080
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs: