version: '3.8'

services:
  neo4j:
    image: neo4j:5.26.15-community-bullseye
    container_name: my_neo4j
    ports:
      - 7474:7474 # ブラウザ経由 password: neo4jpassword, user: neo4j
      - 7687:7687 # プログラム経由
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
      - NEO4J_PLUGINS=["apoc","apoc-extended"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
    networks:
      - mynetwork
  worker-lambda: # Neo4Jノードを制御するAPI
    build:
      context: ./worker_lambda
    container_name: worker-lambda
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4jpassword
      - STATIC_CSV_DIR=./static/target
    ports:
      - 10000:8080
    volumes:
      - ./target_dir:/app/static/target
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5
  init-task: # Neo4jノードの初期化を行うだけのタスク
    image: curlimages/curl:8.8.0
    container_name: init-task
    networks:
      - mynetwork
    depends_on:
      worker-lambda:
        condition: service_healthy
    command: >
      sh -c "
        curl -f http://worker-lambda:8080/ &&
        curl -f -X POST http://worker-lambda:8080/init
      "
networks:
  mynetwork:
    driver: bridge

volumes:
  neo4j_data:
  neo4j_logs: